export const MODULE = {
    CONNECTION_NAME: 'SCHEDULE_QUEUE',
    SETUP_ALIAS: 'queue'
};

export const SERVICE = {
    CONNECTION_NAME: 'SCHEDULE_QUEUE',

};

export const CONTROLLER = {
    CONNECTION_NAME: 'SCHEDULE_QUEUE',
    PATTERN: 'SCHEDULE_QUEUE',
};